env:
  node: true
  browser: true

extends: 
- 'airbnb-base'
overrides: []
parserOptions:
  ecmaVersion: latest

rules: 
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  linebreak-style: ["error", "windows"]
