env:
  es2021: true
extends: 
  - eslint:recommended
  - airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  linebreak-style: ["error", "windows"],
  "no-console": "off"
}
